// Generated by CoffeeScript 2.0.0
(function() {
  var convert, googleNewsAPI, process;

  process = require('process');

  process.chdir(__dirname);

  googleNewsAPI = require('google-news-json');

  convert = require('html-to-text');

  googleNewsAPI.getNews(googleNewsAPI.TOP_NEWS, null, "en-GB", function(err, response) {
    var article, i, len, ref, results;
    ref = response.items;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      article = ref[i];
      console.log(article.title);
      results.push(console.log(convert.convert(article.description, {
        wordwrap: 80,
        selectors: [
          {
            selector: 'a',
            options: {
              ignoreHref: true
            }
          }
        ]
      })));
    }
    return results;
  });

}).call(this);

//# sourceMappingURL=index.js.map
